PM2HAHA/PM2HAHA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PM2HAHA.Models;
using Microsoft.EntityFrameworkCore;
using System.Net;
using Newtonsoft.Json;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq.Expressions;


namespace PM2HAHA.Controllers
{
    
    [Route("Home")]
    public class HomeController : Controller
    {
        int Dataaqi;
        int Dataidx;
        string Dataname;

        [HttpGet]
        public ActionResult<string> Index(int id)
        { 
          
            return View(1);
        }
  

        [Route("")]      // Combines to define the route template "Home"
        [Route("Index")] // Combines to define the route template "Home/Index"
        [Route("/")]     // Doesn't combine, defines the route template ""

      
      //  public async Task<IActionResult> Index()
      //  {
            
            
            

        //    return View();
           

           

        //}
        public IActionResult about()
        {

            
            return View();
        }



        [HttpPost]
        public ActionResult Create(MstUsers std)
        {
            //write code to update student 
            var gg=std;
            return RedirectToAction("About");
        }

        [Route("About")] // Combines to define the route template "Home/About"
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

PM2HAHA/PM2HAHA/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
using PM2HAHA.Models;

namespace PM2HAHA.Controllers
{
    public class LoginController : Controller
    {

        public ActionResult AddOrEdit()
        {
            MstUsers userModel = new MstUsers();
            return View(userModel);
        }


    }
}

PM2HAHA/PM2HAHA/Controllers/MstDataRawsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PM2HAHA.Models;

namespace PM2HAHA.Controllers
{
    public class MstDataRawsController : Controller
    {
        private readonly test_dbContext _context;

        public MstDataRawsController(test_dbContext context)
        {
            _context = context;
        }

        // GET: MstDataRaws
        public async Task<IActionResult> Index()
        {
            return View(await _context.MstDataRaws.ToListAsync());
        }

        // GET: MstDataRaws/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstDataRaw = await _context.MstDataRaws
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mstDataRaw == null)
            {
                return NotFound();
            }

            return View(mstDataRaw);
        }

        // GET: MstDataRaws/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MstDataRaws/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Aqi,Idx,City,Longitude,Latitude,Co,H,No2,O3,P,Pm10,Pm25,So2,T,W,time,CreateAt,UploadAt")] MstDataRaw mstDataRaw)
        {
            if (ModelState.IsValid)
            {
                mstDataRaw.Id = Guid.NewGuid();
                _context.Add(mstDataRaw);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View(mstDataRaw);
        }

        // GET: MstDataRaws/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstDataRaw = await _context.MstDataRaws.FindAsync(id);
            if (mstDataRaw == null)
            {
                return NotFound();
            }
            return View(mstDataRaw);
        }

        // POST: MstDataRaws/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Aqi,Idx,City,Longitude,Latitude,Co,H,No2,O3,P,Pm10,Pm25,So2,T,W,time,CreateAt,UploadAt")] MstDataRaw mstDataRaw)
        {
            if (id != mstDataRaw.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mstDataRaw);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MstDataRawExists(mstDataRaw.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mstDataRaw);
        }

        // GET: MstDataRaws/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstDataRaw = await _context.MstDataRaws
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mstDataRaw == null)
            {
                return NotFound();
            }

            return View(mstDataRaw);
        }

        // POST: MstDataRaws/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var mstDataRaw = await _context.MstDataRaws.FindAsync(id);
            _context.MstDataRaws.Remove(mstDataRaw);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MstDataRawExists(Guid id)
        {
            return _context.MstDataRaws.Any(e => e.Id == id);
        }
    }
}

PM2HAHA/PM2HAHA/Views/Home/Index.cshtml
@model PM2HAHA.Models.MstUsers;
@{
    ViewBag.Title = "Registration";
}
<h2>Registration</h2>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
<div class="alert alert-success">
    <strong>Success!</strong>@ViewBag.Message
</div>
    }
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                @Html.ValidationMessage("EmailExist", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="submit" value="Create" class="btn btn-default" />*@
                <button type="button" onclick="location.href='@Url.Action("AddOrEdit","Login")'">Create</button>
            </div>
        </div>
</div>
        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Error!</strong>@ViewBag.Message
            </div>
        }
    }
}

@*<div>
    @Html.ActionLink("Login", "AddOrEdit","Login")
</div>
<div>
    @Html.ActionLink("PM2.5","Index", "MstDataRaws")
</div>*@


@section Scripts{

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.js"></script>

}