PM2HAHA/PM2HAHA/Models/MstDataRaw.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PM2HAHA.Models
{
   
        [Table("MstDataRaw")]
        public partial class MstDataRaw
    {
        
            [Key, Column("id")]
            public Guid Id { get; set; }

            [Column("aqi")]
            public int Aqi { get; set; }

            [Column("idx")]
            public int Idx { get; set; }
        
            [Column("city")]
            [StringLength(255)]
            public string City { get; set; }

            [Column("longitude")]
            public Decimal Longitude { get; set; }

            [Column("latitude")]
            public Decimal Latitude { get; set; }

            [Column("co")]
             public Decimal Co { get; set; }

            [Column("h")]
            public Decimal H { get; set; }

            [Column("no2")]
            public Decimal No2 { get; set; }

            [Column("o3")]
            public Decimal O3 { get; set; }

            [Column("p")]
             public Decimal P { get; set; }
        
            [Column("pm10")]
            public int Pm10 { get; set; }

            [Column("pm25")]
            public int Pm25 { get; set; }

            [Column("so2")]
            public Decimal So2 { get; set; }

            [Column("t")]
            public Decimal T { get; set; }

            [Column("w")]
            public Decimal W { get; set; }

            [Column("time")]
            public DateTime time { get; set; }

            [Column("CreateAt")]
            public DateTime CreateAt { get; set; }

            [Column("UploadAt")]
             public DateTime UploadAt { get; set; }
    }
    
}

PM2HAHA/PM2HAHA/Controllers/MstDataRawsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PM2HAHA.Models;

namespace PM2HAHA.Controllers
{
    public class MstDataRawsController : Controller
    {
        private readonly test_dbContext _context;

        public MstDataRawsController(test_dbContext context)
        {
            _context = context;
        }

        // GET: MstDataRaws
        public async Task<IActionResult> Index()
        {
            return View(await _context.MstDataRaws.ToListAsync());
        }

        // GET: MstDataRaws/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstDataRaw = await _context.MstDataRaws
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mstDataRaw == null)
            {
                return NotFound();
            }

            return View(mstDataRaw);
        }

        // GET: MstDataRaws/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MstDataRaws/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Aqi,Idx,City,Longitude,Latitude,Co,H,No2,O3,P,Pm10,Pm25,So2,T,W,time,CreateAt,UploadAt")] MstDataRaw mstDataRaw)
        {
            if (ModelState.IsValid)
            {
                mstDataRaw.Id = Guid.NewGuid();
                _context.Add(mstDataRaw);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View(mstDataRaw);
        }

        // GET: MstDataRaws/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstDataRaw = await _context.MstDataRaws.FindAsync(id);
            if (mstDataRaw == null)
            {
                return NotFound();
            }
            return View(mstDataRaw);
        }

        // POST: MstDataRaws/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Aqi,Idx,City,Longitude,Latitude,Co,H,No2,O3,P,Pm10,Pm25,So2,T,W,time,CreateAt,UploadAt")] MstDataRaw mstDataRaw)
        {
            if (id != mstDataRaw.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mstDataRaw);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MstDataRawExists(mstDataRaw.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mstDataRaw);
        }

        // GET: MstDataRaws/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstDataRaw = await _context.MstDataRaws
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mstDataRaw == null)
            {
                return NotFound();
            }

            return View(mstDataRaw);
        }

        // POST: MstDataRaws/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var mstDataRaw = await _context.MstDataRaws.FindAsync(id);
            _context.MstDataRaws.Remove(mstDataRaw);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MstDataRawExists(Guid id)
        {
            return _context.MstDataRaws.Any(e => e.Id == id);
        }
    }
}

PM2HAHA/PM2HAHA/Controllers/MstRsisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PM2HAHA.Models;

namespace PM2HAHA.Controllers
{
    public class MstRsisController : Controller
    {
        private readonly test_dbContext _context;

        public MstRsisController(test_dbContext context)
        {
            _context = context;
        }

        // GET: MstRsis
        public async Task<IActionResult> Index()
        {
            return View(await _context.MstRsis.ToListAsync());
        }

        // GET: MstRsis/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstRsi = await _context.MstRsis
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mstRsi == null)
            {
                return NotFound();
            }

            return View(mstRsi);
        }

        // GET: MstRsis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MstRsis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,period,higilevel,lowlevel,usercreate,CreateAt,UploadAt")] MstRsi mstRsi)
        {
            if (ModelState.IsValid)
            {
                mstRsi.Id = Guid.NewGuid();
                _context.Add(mstRsi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mstRsi);
        }

        // GET: MstRsis/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstRsi = await _context.MstRsis.FindAsync(id);
            if (mstRsi == null)
            {
                return NotFound();
            }
            return View(mstRsi);
        }

        // POST: MstRsis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,period,higilevel,lowlevel,usercreate,CreateAt,UploadAt")] MstRsi mstRsi)
        {
            if (id != mstRsi.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mstRsi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MstRsiExists(mstRsi.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mstRsi);
        }

        // GET: MstRsis/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mstRsi = await _context.MstRsis
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mstRsi == null)
            {
                return NotFound();
            }

            return View(mstRsi);
        }

        // POST: MstRsis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var mstRsi = await _context.MstRsis.FindAsync(id);
            _context.MstRsis.Remove(mstRsi);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MstRsiExists(Guid id)
        {
            return _context.MstRsis.Any(e => e.Id == id);
        }
    }
}

PM2HAHA/PM2HAHA/Views/MstDataRaws/Create.cshtml
@model PM2HAHA.Models.MstDataRaw

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>MstDataRaw</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Aqi" class="control-label"></label>
                <input asp-for="Aqi" class="form-control" />
                <span asp-validation-for="Aqi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idx" class="control-label"></label>
                <input asp-for="Idx" class="form-control" />
                <span asp-validation-for="Idx" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Co" class="control-label"></label>
                <input asp-for="Co" class="form-control" />
                <span asp-validation-for="Co" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="H" class="control-label"></label>
                <input asp-for="H" class="form-control" />
                <span asp-validation-for="H" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="No2" class="control-label"></label>
                <input asp-for="No2" class="form-control" />
                <span asp-validation-for="No2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="O3" class="control-label"></label>
                <input asp-for="O3" class="form-control" />
                <span asp-validation-for="O3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="P" class="control-label"></label>
                <input asp-for="P" class="form-control" />
                <span asp-validation-for="P" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pm10" class="control-label"></label>
                <input asp-for="Pm10" class="form-control" />
                <span asp-validation-for="Pm10" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pm25" class="control-label"></label>
                <input asp-for="Pm25" class="form-control" />
                <span asp-validation-for="Pm25" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="So2" class="control-label"></label>
                <input asp-for="So2" class="form-control" />
                <span asp-validation-for="So2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="T" class="control-label"></label>
                <input asp-for="T" class="form-control" />
                <span asp-validation-for="T" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="W" class="control-label"></label>
                <input asp-for="W" class="form-control" />
                <span asp-validation-for="W" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="time" class="control-label"></label>
                <input asp-for="time" class="form-control" />
                <span asp-validation-for="time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateAt" class="control-label"></label>
                <input asp-for="CreateAt" class="form-control" />
                <span asp-validation-for="CreateAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UploadAt" class="control-label"></label>
                <input asp-for="UploadAt" class="form-control" />
                <span asp-validation-for="UploadAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


PM2HAHA/PM2HAHA/Views/MstDataRaws/Delete.cshtml
@model PM2HAHA.Models.MstDataRaw

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MstDataRaw</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aqi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Aqi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Idx)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Idx)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Co)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Co)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.H)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.H)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.No2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.No2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.O3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.O3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.P)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.P)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pm10)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pm10)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pm25)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pm25)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.So2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.So2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.T)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.T)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.W)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.W)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UploadAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UploadAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PM2HAHA/PM2HAHA/Views/MstDataRaws/Details.cshtml
@model PM2HAHA.Models.MstDataRaw

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>MstDataRaw</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aqi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Aqi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Idx)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Idx)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Co)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Co)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.H)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.H)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.No2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.No2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.O3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.O3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.P)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.P)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pm10)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pm10)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pm25)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pm25)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.So2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.So2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.T)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.T)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.W)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.W)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UploadAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UploadAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PM2HAHA/PM2HAHA/Views/MstDataRaws/Index.cshtml
@model IEnumerable<PM2HAHA.Models.MstDataRaw>

@{
    ViewData["Title"] = "Index";
}

<h2>Data AQI Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Aqi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idx)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Co)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.H)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.No2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.O3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.P)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pm10)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pm25)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.So2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.T)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.W)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UploadAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Aqi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idx)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Longitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Latitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Co)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.H)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.No2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.O3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.P)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pm10)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pm25)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.So2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.T)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.W)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UploadAt)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            
        }
        
    </tbody>
</table>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">

        <button type="button" onclick="location.href='@Url.Action("Index","MstRsis")'">Graph</button>
    </div>
</div>